config/routes.rb
Rails.application.routes.draw do
  root :to => "pages#home"
  get '/new_item' => 'pages#new_item'
  post '/new_item' => 'pages#create'

  resources :users, :only => [:new, :create, :index]
  
  resources :songs
  get '/dislike' => 'songs#dislike'
  get '/like/:id' => 'songs#like'
  get '/library_songs' => 'songs#library_songs'

  resources :albums

  resources :artists

  get '/login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'login' => 'sessions#destroy'
end

app/models/album.rb
class Album < ApplicationRecord
    belongs_to :artist
    has_many :songs
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artist.rb
class Artist < ApplicationRecord
    has_many :albums
    has_many :songs
end

app/models/song.rb
class Song < ApplicationRecord
    belongs_to :artist
    belongs_to :album
    has_and_belongs_to_many :users
end

app/models/user.rb
class User < ApplicationRecord
    has_and_belongs_to_many :songs
    has_many :artists, :through => :songs
    has_many :albums, :through => :songs
    has_secure_password
    validates :email, presence: true, uniqueness: true
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
    before_action :get_album, only: [:show]

    def index
        @albums = @current_user.albums
    end

    def show
    end

    private

    def get_album
        @album = Album.find(params[:id])
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :get_current_user

    def get_current_user
        @current_user = User.find_by :id => session[:user_id] if session[:user_id].present?
        session[:user_id] = nil unless @current_user.present?
    end
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
    before_action :get_artist, only: [:show]

    def index
        @artists = @current_user.artists
    end

    def show
    end

    private

    def get_artist
        @artist = Artist.find(params[:id])
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

	def home
		@song_to_be_displayed = Song.offset(rand(Song.count)).first
	end

	def new_item
	end

	def create
		fetched_song = begin
			spotify_id = params[:url].scan(/https?:\/\/(?:open\.)?spotify\.com\/track\/(\w*)/)[0][0]
			RSpotify::Track.find(spotify_id)
		rescue Exception => e
			flash[:alert] = "We coudn't find a song through this URL :( - Make sure you are copying a URL's track from Spotify."
			redirect_to new_item_path
			return
		end

		if Song.exists?(spotify_id: fetched_song.id)
			flash[:alert] = "This song is already in our database."
 		    redirect_to new_item_path
			return
		elsif !fetched_song.preview_url
			flash[:alert] = "Unfortunately this song doesn't have a sample track :("
 		    redirect_to new_item_path
			return
		else
			artist = create_artist(fetched_song.artists.first)
			album = create_album(fetched_song.album, artist)
			song = Song.create :name => fetched_song.name, :spotify_id => fetched_song.id, :preview_url => fetched_song.preview_url, :artist => artist, :album => album
			@current_user.songs << song
			flash[:notice] = "Thanks for feeding our music library!"
			redirect_to new_item_path
		end
	end

	private
	
	def create_artist(artist)
		fetched_artist = Artist.where(spotify_id: artist.id).first
		if !fetched_artist 
        	Artist.create :name => artist.name, :spotify_id => artist.id
    	else 
			fetched_artist
		end
	end

	def create_album(album, artist)
		fetched_album = Album.where(spotify_id: album.id).first
		if !fetched_album
			Album.create :name => album.name, :spotify_id => album.id, :image => album.images.first['url'], :artist => artist
		else
			fetched_album
		end
	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def new
    end

    def create
        user = User.find_by :email => params[:email]
        if user.present? && user.authenticate(params[:password])
            session[:user_id] = user.id
            redirect_to root_path
        else
            flash[:alert] = "User not found. Check your email or password."
            redirect_to login_path
        end
    end

    def destroy
        session[:user_id] = nil
        flash[:notice] = "You have successfully logged out."
        redirect_to login_path
    end
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
    before_action :get_song, only: [:show, :destroy, :like]

    def index
        @songs = @current_user.songs
    end

    def show
    end

    def destroy
        @current_user.songs.delete(@song)
        redirect_to songs_path
    end

    def dislike
        redirect_to root_path
    end

    def like
        if !@current_user.songs.exists?(spotify_id: @song.spotify_id)
            @current_user.songs << @song
        end
        redirect_to root_path
    end

    def library_songs
        @songs = Song.all
    end

    private
   
    def get_song
        @song = Song.find(params[:id])
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new user_params
    if @user.save
      # @user.email = @user.email.downcase!
      # @user.name = @user.name.capitalize!
      session[:user_id] = @user.id 
      redirect_to root_path
    else
      render :new
    end
  end

  def index
    # for admin only, grab all users
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def active_class(link_path)
        current_page?(link_path) ? "active" : ""
    end

    def flash_class(level)
        bootstrap_alert_class = {
          "success" => "alert-success",
          "error" => "alert-danger",
          "notice" => "alert-info",
          "alert" => "alert-danger",
          "warn" => "alert-warning"
        }
        bootstrap_alert_class[level]
      end
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/albums/index.html.erb
<% if @albums.empty? %>
    <h1>You don't have any albums yet :( </h1>
<% else %>
    <h1>Your albums</h1>
    <div class='row albums-index'>
    <% @albums.each do |album| %>
        <div class="card col-md-4" style="width: 18rem;">
            <%= image_tag album.image %>
            <div class="card-body">
                <p class="card-text"><%= link_to "#{album.name}", album_path(album.id) %></p>
            </div>
        </div>
    <% end %>
    </div>  
<% end %>

app/views/albums/show.html.erb
<div class="overflow-auto albums-index">
    <%= image_tag @album.image, class: 'one-album' %>

    <h2><%= @album.name %></h2>
    <p><%= @album.released_year.strftime("%B %d, %Y") %></p>
    <h3>Artist</h3>
    <%= link_to "#{@album.artist.name}", artist_path(@album.artist.id), class: 'second after' %>
    <h3 class="songs">Songs you have from this album</h3>
    <div class="overflow-auto">
    <% @album.songs.each do |song| %>
        <ul>
            <li><%= link_to "#{song.name}", song_path(song.id) %></li>
        </ul>
    <% end %>
    </div>
</div>

app/views/artists/index.html.erb
<% if @artists.empty? %>
    <h1>You don't have any artists yet :( </h1>
<% else %>
    <h1>Artists that you have songs from</h1>

    <% @artists.each do |artist| %>
        <ul>
            <li><%= link_to "#{artist.name}", artist_path(artist.id) %></li>
        </ul>
    <% end %>
<% end %>

app/views/artists/show.html.erb
<div class="artists-index">
    <h1><%= @artist.name %></h1>

    <h3 class="songs">Albums you have from this artist</h3>

    <% @artist.albums.each do |album| %>
            <h2><%= link_to "#{album.name}", album_path(album.id) %></h2>
            <h4>Songs</h4>
            <% album.songs.each do |song| %>
                <ul>
                    <li><%= link_to "#{song.name}", song_path(song.id) %></li>
                </ul>
            <% end %>
    <% end %>

    <% if @artist.info %>
        <h4>Info</h4>
        <p><%= @artist.info %></p>
    <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MusicLibrary</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta charset="utf-8">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">

      <%= render "shared/header" %>

      <%= yield %>

    </div>
     <%= render "shared/footer"  %>
  </body>
</html>

app/views/pages/home.html.erb
<% if @current_user.present? %>
    <h1 class="text-center">Discover new songs</h1>
    <hr class="hr" />

    <div class="row .align-items-center">
        <div class="col-md-3 like-dislike-container">
            <%= link_to image_tag("dislike.png", class: 'fa-lg'), dislike_path  %>
        </div>

        <div class="col-md-6">
            <div class="player-background">
                <div class="player-image">
                    <img class="album-player thumbnail-box-shadow rounded float-start" src="<%= @song_to_be_displayed.album.image %>" alt="album">
                </div>
                <div class="player-container">
                    <h5><%= @song_to_be_displayed.name %></h5>
                    <p><%= @song_to_be_displayed.album.name %></p>
                    <audio controls>
                        <source src="<%= @song_to_be_displayed.preview_url %>" type="audio/ogg">
                        <source src="<%= @song_to_be_displayed.preview_url %>" type="audio/mpeg">
                        <source src="<%= @song_to_be_displayed.preview_url %>" type="audio/wav">
                    </audio>
                </div>
            </div>
        </div>
        <div class="col-md-3 like-dislike-container">
            <%= link_to image_tag("like.png", class: 'fa-lg'), "/like/#{@song_to_be_displayed.id}"%>
        </div>
    </div>

<% else %>

    <div class='row .align-items-center'>
        <div class='col-md-6'>
            <div class='home-container-left'>
                <h1>SoundWave</h1>
                <h4>You don't need to listen for an entire song to know if you like it or not.</h4>
                
                <hr>
                <h5>If you still is not a member, sign up to dive in in this idea!</h5>
                <%= link_to 'Sign Up', new_user_path %>
            </div>
        </div>
    </div>
<% end %>

app/views/pages/new_item.html.erb
<div class="new-item-container">
    <h3>We appreciate your help by adding new songs. Doing so, we can build a strong database and the music community can find more songs!</h3>

    <% flash.each do |key, msg| %>
        <div class="alert <%= flash_class(key) %> alert-dismissible fade show text-center"> 
            <%= msg %> 
        </div>
    <% end %>


    <h4 style="margin-bottom: 2em;">You just need to grab the Spotify's link from the song you want.</h4>

    <div class="register-photo">
        <div class="form-container">
            <%= form_tag new_item_path do %>
                <div class="form-group">
                    <%= url_field_tag :url, nil, placeholder: 'URL', :class => 'form-control' %>
                </div>
                <div class="form-group">
                    <%= submit_tag 'Feed database', class: 'btn btn-primary btn-block mb-4'  %>
                </div>
            <% end %>
        </div>
    </div>
</div>

app/views/shared/_footer.html.erb
<div class="footer-padding"></div>
<footer class="bg-light text-center text-lg-start fixed-bottom">
    <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2);">
        2022 | SoundWave
    </div>
</footer>

app/views/shared/_header.html.erb
<header>
 <div>
  <%= render "shared/nav" %>
 </div>
</header>

app/views/shared/_nav.html.erb
<nav class="navbar navbar-expand-lg bg-light shadow p-3 mb-5 rounded sticky-top">
    <div class="container-fluid">
    <%= link_to image_tag("logo.png", class: 'img-logo'), root_path %>
        <button class="navbar-toggler collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
         <span class="navbar-toggler-icon"></span>
        </button>
    <div class="navbar-collapse collapse" id="navbarNavAltMarkup">
        <ul class="navbar-nav ms-auto mb-2 mb-lg-0 navbar-nav-scroll">
       <% if @current_user.present? %>
            <li class="nav-item">
            <p>Hello, <%= @current_user.name.capitalize %></p>
            </li>
            <li class="nav-item dropdown">
                <a class='nav-link dropdown-toggle' id='navbarDropdown' role='button' data-bs-toggle='dropdown' aria-expanded='false'>My Library</a>
                <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <li>
                        <%= link_to 'Songs', songs_path, class: 'nav-link' %>
                    </li>
                    <li>
                        <%= link_to 'Artists', artists_path, class: 'nav-link' %>
                    </li>
                    <li>
                        <%= link_to 'Albums', albums_path, class: 'nav-link' %>
                    </li>
                    <li><hr class="dropdown-divider" /></li>
                    <li>
                        <%= link_to 'SoundWave songs library', library_songs_path, class: 'nav-link' %>
                    </li>
                </ul>
            </li>
            <li class="nav-item <%= active_class('new_item_path') %>">
            <%= link_to 'Feed database', new_item_path, class: 'nav-link' %>
            </li>
            <li class="nav-item <%= active_class('login_path') %>">
            <%= link_to 'Sign Out', login_path, :method => 'delete', class: 'nav-link' %>
            </li>
        <% else %>
            <li class="nav-item <%= active_class('new_user_path') %>">
            <%= link_to 'Sign Up', new_user_path, class: 'nav-link' %>
            </li>
            <li class="nav-item <%= active_class('login_path') %>">
            <%= link_to 'Sign In', login_path, class: 'nav-link' %>
            </li>
        <% end %>
        </ul>
    </div>
    </div>
</nav>

app/views/songs/_index_songs.html.erb
<div class='row'>
    <% @songs.each do |song| %>
        <div class="col-md-8 user-index-song">
            <li><%= link_to "#{song.name}", song_path(song.id) %></li>
        </div>
        <div class="col-md-4 user-index-player">
            <audio controls>
                <source src="<%= song.preview_url %>" type="audio/ogg">
                <source src="<%= song.preview_url %>" type="audio/mpeg">
                <source src="<%= song.preview_url %>" type="audio/wav">
            </audio>
        </div>
    <% end %>
</div>

app/views/songs/index.html.erb
<% if @songs.empty? %>
    <h1>You don't have any songs liked yet :( </h1>
    <h5 style="color: white;">You can add songs by either liking some of them on the home page or by feeding our database.</h5>
<% else %>

    <h1>Here are songs that you like</h1>

    <%= render 'index_songs' %>
<% end %>

app/views/songs/library_songs.html.erb
<%= render 'index_songs' %>

app/views/songs/show.html.erb
<div class="songs-index">
    <h1><%= @song.name %></h1>

    <h3>Artist</h3>
    <p><%= link_to "#{@song.artist.name}", artist_path(@song.artist.id) %></p>
    <h3>Album</h3>
    <li><%= link_to "#{@song.album.name}", album_path(@song.album.id) %></li>

    <div>
        <%= link_to 'Delete Song', song_path, :method => 'delete', :data => {:confirm => 'Are you sure?'}, class: 'btn btn-primary btn-block mb-4' %> 
    </div>
</div>

app/views/users/new.html.erb
<% if @user.errors.any? %>
  <div class="alert alert-info">
    <div>
      Please, fix the following <%= pluralize(@user.errors.count, "error") %>:
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<div class="register-photo">
  <div class="form-container">
    <div class="image-holder"></div>

    <%= form_for @user do |f| %>

      <h2 class="text-center"><strong>Create</strong> an account.</h2>
        <div class="form-group">          
            <%= f.text_field :name, :class => 'form-control', :placeholder => 'Name' %>
        </div>
      
        <div class="form-group">
            <%= f.email_field :email, :class => 'form-control', :placeholder => 'Email' %>
        </div>
      
        <div class="form-group">
            <%= f.password_field :password, :class => 'form-control', :placeholder => 'Password' %>
        </div>

        <div class="form-group">
            <%= f.password_field :password_confirmation, :class => 'form-control', :placeholder => 'Confirm' %>
        </div>

        <div class="form-group">
          <%= f.submit 'Join!', :class => 'btn btn-primary btn-block mb-4' %>
        </div>

        <p>Already have an account? Sign in  <%= link_to 'here.', login_path, class: 'here' %></p>
    <% end %>

  </div>
</div>